### ISSUE TITLE
mainwindow.h file not updated with mainwindow.cpp

### ISSUE THREAD

**Issue by rshatz** [maurime2/CHECKERS_CSC17B_48941#1]
I can't seem to push updated version of mainwindow.h to the repository. mainwindow.h is out of date with mainwindow.cpp.
Also can not push image files for icons.

**Comment by maurime2** [comment]
Send it to me in a zip,file and I'll post it

On Friday, October 9, 2015, Ritchie notifications@github.com wrote:

> I can't seem to push updated version of mainwindow.h to the repository.
> mainwindow.h is out of date with mainwindow.cpp.
> Also can not push image files for icons.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/maurime2/CHECKERS_CSC17B_48941/issues/1.

## 

Mauricio S. Perez
[p] 831.262.3423
[e] MauriMe2@gmail.com

**Comment by rshatz** [comment]
fixed
