### ISSUE TITLE
delete guitar tablature files  

### ISSUE THREAD

**Issue by rshatz** [maurime2/CHECKERS_CSC17B_48941#2]
please delete guitar tablature files. They are not needed.

**Comment by maurime2** [comment]
Ok

On Friday, October 9, 2015, Ritchie notifications@github.com wrote:

> please delete guitar tablature files. They are not needed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/maurime2/CHECKERS_CSC17B_48941/issues/2.

## 

Mauricio S. Perez
[p] 831.262.3423
[e] MauriMe2@gmail.com

**Comment by rshatz** [comment]
Done
